spring:
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-circular-references: true

  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

#  shell:
#    interactive:
#      enabled: false
