# Use root/example as user/password credentials
# docker-compose up --build
version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    container_name: otus_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: library
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro