spring:
  output:
    ansi:
      enabled: ALWAYS

  messages:
    encoding: UTF-8
  data:
    mongodb:
      database: library
      username: root
      password: example
      host: localhost
      port: 27017
      authentication-database: admin
  main:
    allow-bean-definition-overriding: true

server.error.include-message: always

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
#debug: true
