# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

# Define services
services:
  db:
    container_name: test-task-manager
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: